Repository merely-useful/py-rse, pull requests merged in 2019-09, with the labels that each got.

#155 revision to python version control
  _py.yml
  figures/py-version-control/tmp-commit-cycle.jpeg
  figures/py-version-control/tmp-remote.jpeg
  figures/py-version-control/tmp-revert-cycle.jpeg
  keypoints/py-version-control.md
  objectives/py-version-control.md
  py-version-control.Rmd
  questions/py-version-control.md
Labels: Novice Python

#180 Intermediate section on verification/testing
  _bookdown.yml
  figures/rse-verification/concept.pdf
  figures/rse-verification/concept.png
  figures/rse-verification/concept.svg
  figures/rse-verification/rse-verification.drawio
  keypoints/verify.md
  rse-verify.Rmd
Labels: Intermediate, work in progress

#138 revisions to novice python data manipulation
  keypoints/py-data-manipulation.md
  objectives/py-data-manipulation.md
  py-data-manipulation.Rmd
  questions/py-data-manipulation.md
Labels: Novice Python

#209 Add data to website
  Makefile
  rse-py-package.Rmd
Labels: infrastructure
