Repository merely-useful/py-rse, pull requests merged in 2019-10, with the labels that each got.

#214 Remove leftover chapters after RSE goals update
  Makefile
  _rse.yml
  appendix.Rmd
  pacing.Rmd
  process.Rmd
  remote.Rmd
  tools.Rmd
Labels: Intermediate

#164 revisions to command line git
  Makefile
  _rse.yml
  branches.Rmd
  keypoints/rse-advanced-git.md
  keypoints/rse-cmdline-git.md
  objectives/rse-advanced-git.md
  objectives/rse-cmdline-git.md
  questions/rse-advanced-git.md
  questions/rse-cmdline-git.md
  rse-advanced-git.Rmd
  rse-cmdline-git.Rmd
Labels: Intermediate, work in progress

#227 docs and refactor are mostly covered in other locations, so they're redundant now.
  Makefile
  _rse.yml
  docs.Rmd
  keypoints/docs.md
  keypoints/refactor.md
  refactor.Rmd
Labels: Intermediate

#225 Jupyerlab and jupytext
  py-jupyter.md
Labels: Novice Python
