Repository merely-useful/py-rse, pull requests merged in 2019-07, with the labels that each got.

#136 moving path and data material
  novice-goals.Rmd
  objectives/reproducibility.md
  py-reproducibility.Rmd
Labels: Novice Python

#123 revisions to rse-bash
  Makefile
  _bookdown.yml
  keypoints.Rmd
  keypoints/bash.md
  keypoints/shell.md
  objectives.Rmd
  objectives/bash.md
  objectives/shell.md
  questions/bash.md
  rse-bash.Rmd
Labels: Intermediate

#131 Bibliography fixes
  _bookdown.yml
  _output.yml
  csl/jcb.csl
  index.Rmd
  logging.Rmd
  references.Rmd
Labels: infrastructure

#121 revisions to novice python getting started
  gloss.md
  keypoints/py-getting-started.md
  objectives/py-getting-started.md
  py-getting-started.Rmd
  questions/py-getting-started.md
Labels: Novice Python

#143 revisions to publishing
  _bookdown.yml
  objectives/publish.md
  publish.Rmd
  questions/publish.md
  rse-publish.Rmd
Labels: Intermediate, work in progress
