Repository merely-useful/py-rse, pull requests merged in 2019-05, with the labels that each got.

#46 Minor updates to CI
  README.md
  _build.R
Labels: infrastructure

#51 Insert graphics simply
  .config.yml
  DESCRIPTION
  README.md
  _bookdown.yml
  _common.R
  syndicate.Rmd
Labels: infrastructure

#54 Detail in README about protected branch
  README.md
Labels: infrastructure

#79 Add Python support for bookdown and included in travis
  .travis.yml
  DESCRIPTION
  README.md
  _common.R
  verify.Rmd
Labels: enhancement, infrastructure

#91 Do not save 'birds.png' in Git.
  .gitignore
  birds.png
Labels: Novice R, enhancement
