Repository merely-useful/py-rse, pull requests merged in 2019-06, with the labels that each got.

#85 Generic introduction for novice material.
  gloss.md
  novice-r-intro.Rmd
Labels: Novice Python, Novice R

#124 Rename novice-r-practice/ to data/
  data/home-range-database.csv
  data/measurements.csv
  data/person.csv
  data/site.csv
  data/visited.csv
  novice-r-practice.Rmd
Labels: infrastructure

#125 Simple visual separation of Rmd files in _bookdown.yml file
  _bookdown.yml
Labels: infrastructure

#90 R packaging
  .gitignore
  _bookdown.yml
  etc/links.md
  figures/FIXME.png
  figures/rse-r-package/rse-r-package.drawio
  figures/rse-r-package/rse-r-package.pdf
  figures/rse-r-package/rse-r-package.svg
  gloss.md
  keypoints/rse-r-package.md
  objectives/rse-r-package.md
  questions/rse-r-package.md
  rse-r-package.Rmd
  rse-r-testing.Rmd
Labels: Intermediate, work in progress

#129 links.md doesn't need to be included as child, moved into parent folder
  _bookdown.yml
  automate.Rmd
  backlog.Rmd
  branches.Rmd
  configure.Rmd
  docs.Rmd
  finale.Rmd
  inclusive.Rmd
  index.Rmd
  integrate.Rmd
  links.md
  logging.Rmd
  novice-goals.Rmd
  novice-py-intro.Rmd
  novice-r-intro.Rmd
  novice-r-practice.Rmd
  pacing.Rmd
  process.Rmd
  project.Rmd
  publish.Rmd
  py-package.Rmd
  refactor.Rmd
  references.Rmd
  remote.Rmd
  rse-intro.Rmd
  rse-r-testing.Rmd
  rules.Rmd
  shell.Rmd
  style.Rmd
  syndicate.Rmd
  teamwork.Rmd
  tools.Rmd
  unit.Rmd
  verify.Rmd
Labels: infrastructure
