Repository merely-useful/py-rse, pull requests merged in 2019-08, with the labels that each got.

#100 Novice R reproducibility chapter
  _bookdown.yml
  book.bib
  figures/r-reproducibility/code-sharing-steps.png
  figures/r-reproducibility/knit-button-rstudio.png
  gloss.md
  includes/r-reproducibility/exercise-markdown.Rmd
  includes/r-reproducibility/exercise-markdown.html
  keypoints/r-reproducibility.md
  links.md
  objectives/r-reproducibility.md
  objectives/reproducibility.md
  questions/r-reproducibility.md
  r-reproducibility.Rmd
Labels: Novice R

#169 Contributing guidelines update
  .github/CONTRIBUTING.md
  README.md
  _bookdown.yml
  contribute.md
Labels: infrastructure

#170 Py intro suggestions
  py-getting-started.Rmd
Labels: Novice Python
