Repository merely-useful/py-rse, pull requests merged in 2020-03, with the labels that each got.

#324 modify novice python data manipulation
  figures/py-data-manipulation/NYC-dog-licenses-snapshot.PNG
  py/data-manipulation.Rmd
Labels: Novice Python

#335 Testing to see if Travis builds other pdfs
  Makefile
Labels: bug, work in progress

#307 Zipf changes for the automation chapter
  figures/rse-automate/make-dependency-graph.png
  links.md
  py-rse/automate.Rmd
  zipfs-law/Makefile
Labels: Intermediate

#327 py-rse-teams updates for Zipf's Law
  py-rse/teams.Rmd
Labels: Intermediate

#338 Reduce novel texts
  figures/py-rse-scripting/emma.png
  figures/py-rse-scripting/jane_eyre.png
  py-rse/automate.Rmd
  py-rse/bash-advanced.Rmd
  py-rse/bash-basics.Rmd
  py-rse/py-scripting.Rmd
  py-rse/solutions.Rmd
  zipfs-law/Makefile
  zipfs-law/bin/collate.py
  zipfs-law/bin/countwords.py
  zipfs-law/bin/mymodule.py
  zipfs-law/bin/plotcounts.py
  zipfs-law/bin/plotcounts_config.py
  zipfs-law/bin/plotcounts_fit.py
  zipfs-law/bin/plotcounts_log.py
  zipfs-law/bin/plotcounts_rank.py
  zipfs-law/data/anne_of_green_gables.txt
  zipfs-law/data/common_sense.txt
  zipfs-law/data/count_of_monte_cristo.txt
  zipfs-law/data/emma.txt
  zipfs-law/data/ethan_frome.txt
  zipfs-law/data/life_of_frederick_douglass.txt
  zipfs-law/data/mysterious_affair_at_styles.txt
  zipfs-law/data/pride_and_prejudice.txt
  zipfs-law/data/treasure_island.txt
Labels: Intermediate

#306 Working narrative into py-rse/git-cmdline.Rmd
  figures/py-rse-git-cmdline/plot-initial.png
  figures/py-rse-git-cmdline/plot-loglog.png
  figures/py-rse-git-cmdline/repo-history.png
  figures/py-rse-git-cmdline/repo-link.png
  links.md
  py-rse-index.Rmd
  py-rse/git-cmdline.Rmd
Labels: Intermediate

#317 Revision to correctness chapter with more exercises
  .travis.yml
  _output.yml
  _py-rse.yml
  figures/rse-correct/number-spacing.png
  py-rse/correct.Rmd
  r-rse/correct.Rmd
Labels: Intermediate
